/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\workspace\\dobyte\\due-docs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-337d163c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-337d163c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-b001360e",
    path: "/guide/v2/1.3.contribute.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b001360e").then(next)
    },
  },
  {
    name: "v-787cfd19",
    path: "/guide/v2/1.2.examples.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-787cfd19").then(next)
    },
  },
  {
    name: "v-24a22d96",
    path: "/guide/v2/1.1.quick-start.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-24a22d96").then(next)
    },
  },
  {
    name: "v-27c6bcd9",
    path: "/guide/v2/2.1.architecture.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27c6bcd9").then(next)
    },
  },
  {
    name: "v-132f2e99",
    path: "/guide/v2/2.10.mode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-132f2e99").then(next)
    },
  },
  {
    name: "v-f8cd1cce",
    path: "/guide/v2/2.11.error.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f8cd1cce").then(next)
    },
  },
  {
    name: "v-112a3f41",
    path: "/guide/v2/2.12.rolling-update.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-112a3f41").then(next)
    },
  },
  {
    name: "v-78347559",
    path: "/guide/v2/2.2.protocol.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-78347559").then(next)
    },
  },
  {
    name: "v-30bba521",
    path: "/guide/v2/2.3.route.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30bba521").then(next)
    },
  },
  {
    name: "v-161a85fb",
    path: "/guide/v2/2.4.bind-gate.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-161a85fb").then(next)
    },
  },
  {
    name: "v-91e8cbea",
    path: "/guide/v2/2.5.bind-node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-91e8cbea").then(next)
    },
  },
  {
    name: "v-3e27a0cf",
    path: "/guide/v2/2.6.single-thread.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e27a0cf").then(next)
    },
  },
  {
    name: "v-59af357b",
    path: "/guide/v2/2.7.multiple-coroutines.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59af357b").then(next)
    },
  },
  {
    name: "v-67cf453f",
    path: "/guide/v2/2.8.actor.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67cf453f").then(next)
    },
  },
  {
    name: "v-325ab3bf",
    path: "/guide/v2/2.9.etc.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-325ab3bf").then(next)
    },
  },
  {
    name: "v-6fce4e79",
    path: "/guide/v2/3.1.gate.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6fce4e79").then(next)
    },
  },
  {
    name: "v-34b5c4b9",
    path: "/guide/v2/3.2.node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34b5c4b9").then(next)
    },
  },
  {
    name: "v-1084db0e",
    path: "/guide/v2/3.3.mesh.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1084db0e").then(next)
    },
  },
  {
    name: "v-63fed0d9",
    path: "/guide/v2/4.1.registry.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63fed0d9").then(next)
    },
  },
  {
    name: "v-85abd472",
    path: "/guide/v2/3.4.web.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-85abd472").then(next)
    },
  },
  {
    name: "v-c93da84e",
    path: "/guide/v2/4.2.config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c93da84e").then(next)
    },
  },
  {
    name: "v-24338093",
    path: "/guide/v2/4.3.network.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-24338093").then(next)
    },
  },
  {
    name: "v-0dd2934a",
    path: "/guide/v2/4.4.transport.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0dd2934a").then(next)
    },
  },
  {
    name: "v-5b6ca83a",
    path: "/guide/v2/4.5.log.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5b6ca83a").then(next)
    },
  },
  {
    name: "v-5b4ccb25",
    path: "/guide/v2/4.6.cache.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5b4ccb25").then(next)
    },
  },
  {
    name: "v-c4264dce",
    path: "/guide/v2/4.7.crypto.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c4264dce").then(next)
    },
  },
  {
    name: "v-0d40aa99",
    path: "/guide/v2/4.8.eventbus.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d40aa99").then(next)
    },
  },
  {
    name: "v-3e753219",
    path: "/guide/v2/4.9.lock.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e753219").then(next)
    },
  },
  {
    name: "v-44839cb9",
    path: "/guide/v2/5.1.gorm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44839cb9").then(next)
    },
  },
  {
    name: "v-cfdec98e",
    path: "/guide/v2/5.2.redis.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cfdec98e").then(next)
    },
  },
  {
    name: "v-cd672476",
    path: "/guide/v2/5.3.mongo.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cd672476").then(next)
    },
  },
  {
    name: "v-5bc3a49d",
    path: "/guide/v2/5.4.jwt.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5bc3a49d").then(next)
    },
  },
  {
    name: "v-59650e12",
    path: "/guide/v2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59650e12").then(next)
    },
  },
  {
    path: "/guide/v2/index.html",
    redirect: "/guide/v2/"
  },
  {
    name: "v-e8f5e2f6",
    path: "/join/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e8f5e2f6").then(next)
    },
  },
  {
    path: "/join/index.html",
    redirect: "/join/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]