/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "due",
  "description": "due - 基于Go语言开发的高性能分布式游戏服务器框架",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/icon.png"
      }
    ],
    [
      "script",
      {
        "type": "text/javascript"
      },
      "var _hmt = _hmt || [];\n        (function() {\n            var hm = document.createElement(\"script\");\n            hm.src = \"https://hm.baidu.com/hm.js?c77f15742ac7b6883fb18421ee33a702\";\n            var s = document.getElementsByTagName(\"script\")[0];\n            s.parentNode.insertBefore(hm, s);\n        })();\n      "
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3c8772"
      }
    ],
    [
      "meta",
      {
        "property": "og:url",
        "content": "https://dobyte.github.io"
      }
    ],
    [
      "meta",
      {
        "property": "og:type",
        "content": "website"
      }
    ],
    [
      "meta",
      {
        "property": "og:title",
        "content": "due"
      }
    ],
    [
      "meta",
      {
        "property": "og:description",
        "content": "due - 基于Go语言开发的高性能分布式游戏服务器框架"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.png",
        "actionText": "快速上手 →",
        "actionLink": "/guide/v2/",
        "heroText": "高性能分布式游戏服务器框架",
        "tagline": "基于Go语言开发的高性能分布式游戏服务器框架",
        "sidebar": "auto",
        "features": [
          {
            "title": "分布式",
            "details": "框架整体围绕着分布式应用场景构建，能够满足任何类型的分布式游戏和应用的开发。"
          },
          {
            "title": "模块化",
            "details": "框架借鉴了 Kratos 的模块设计思路，开发者可根据自身业务特点选用不同的模块来实现功能。"
          },
          {
            "title": "高性能",
            "details": "框架原生实现了一套集群内部的通信方案，普通机器单线程也能轻松实现20W+的TPS。"
          },
          {
            "title": "标准化",
            "details": "框架原生提供标准化的开发规范，无论多么复杂的项目也能轻松应对。"
          },
          {
            "title": "易扩展",
            "details": "采用良好的接口设计，方便开发者设计实现自有功能。"
          },
          {
            "title": "稳定性",
            "details": "所有发布的正式版本均已通过内部真实业务的严格测试，具备较高的稳定性。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2025 dobyte"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-337d163c",
      "path": "/"
    },
    {
      "title": "1.3 协作贡献",
      "frontmatter": {},
      "regularPath": "/guide/v2/1.3.contribute.html",
      "relativePath": "guide/v2/1.3.contribute.md",
      "key": "v-b001360e",
      "path": "/guide/v2/1.3.contribute.html",
      "headers": [
        {
          "level": 2,
          "title": "1.3.1 规范说明",
          "slug": "_1-3-1-规范说明"
        },
        {
          "level": 2,
          "title": "1.3.2 贡献代码",
          "slug": "_1-3-2-贡献代码"
        },
        {
          "level": 2,
          "title": "1.3.3 贡献者",
          "slug": "_1-3-3-贡献者"
        }
      ]
    },
    {
      "title": "1.2 项目示例",
      "frontmatter": {},
      "regularPath": "/guide/v2/1.2.examples.html",
      "relativePath": "guide/v2/1.2.examples.md",
      "key": "v-787cfd19",
      "path": "/guide/v2/1.2.examples.html"
    },
    {
      "title": "1.1 快速开始",
      "frontmatter": {},
      "regularPath": "/guide/v2/1.1.quick-start.html",
      "relativePath": "guide/v2/1.1.quick-start.md",
      "key": "v-24a22d96",
      "path": "/guide/v2/1.1.quick-start.html",
      "headers": [
        {
          "level": 2,
          "title": "1.1.1 Go编译器安装",
          "slug": "_1-1-1-go编译器安装"
        },
        {
          "level": 2,
          "title": "1.1.2 工具链安装",
          "slug": "_1-1-2-工具链安装"
        }
      ]
    },
    {
      "title": "2.1 架构设计",
      "frontmatter": {},
      "regularPath": "/guide/v2/2.1.architecture.html",
      "relativePath": "guide/v2/2.1.architecture.md",
      "key": "v-27c6bcd9",
      "path": "/guide/v2/2.1.architecture.html"
    },
    {
      "title": "2.10 运行模式",
      "frontmatter": {},
      "regularPath": "/guide/v2/2.10.mode.html",
      "relativePath": "guide/v2/2.10.mode.md",
      "key": "v-132f2e99",
      "path": "/guide/v2/2.10.mode.html",
      "headers": [
        {
          "level": 2,
          "title": "2.10.1 基本介绍",
          "slug": "_2-10-1-基本介绍"
        },
        {
          "level": 2,
          "title": "2.10.2 指定模式",
          "slug": "_2-10-2-指定模式"
        },
        {
          "level": 2,
          "title": "2.10.3 相关接口",
          "slug": "_2-10-3-相关接口"
        }
      ]
    },
    {
      "title": "2.11 错误处理",
      "frontmatter": {},
      "regularPath": "/guide/v2/2.11.error.html",
      "relativePath": "guide/v2/2.11.error.md",
      "key": "v-f8cd1cce",
      "path": "/guide/v2/2.11.error.html",
      "headers": [
        {
          "level": 2,
          "title": "2.11.1 基本介绍",
          "slug": "_2-11-1-基本介绍"
        },
        {
          "level": 2,
          "title": "2.11.2 错误接口",
          "slug": "_2-11-2-错误接口"
        },
        {
          "level": 2,
          "title": "2.11.3 错误码接口",
          "slug": "_2-11-3-错误码接口"
        },
        {
          "level": 2,
          "title": "2.11.4 示例代码",
          "slug": "_2-11-4-示例代码"
        }
      ]
    },
    {
      "title": "2.12 滚动更新",
      "frontmatter": {},
      "regularPath": "/guide/v2/2.12.rolling-update.html",
      "relativePath": "guide/v2/2.12.rolling-update.md",
      "key": "v-112a3f41",
      "path": "/guide/v2/2.12.rolling-update.html",
      "headers": [
        {
          "level": 2,
          "title": "2.12.1 基本介绍",
          "slug": "_2-12-1-基本介绍"
        },
        {
          "level": 2,
          "title": "2.12.2 网关服更新",
          "slug": "_2-12-2-网关服更新"
        },
        {
          "level": 2,
          "title": "2.12.3 节点服更新",
          "slug": "_2-12-3-节点服更新"
        },
        {
          "level": 2,
          "title": "2.12.4 网格服更新",
          "slug": "_2-12-4-网格服更新"
        }
      ]
    },
    {
      "title": "2.2 协议设计",
      "frontmatter": {},
      "regularPath": "/guide/v2/2.2.protocol.html",
      "relativePath": "guide/v2/2.2.protocol.md",
      "key": "v-78347559",
      "path": "/guide/v2/2.2.protocol.html",
      "headers": [
        {
          "level": 2,
          "title": "2.2.1 心跳包",
          "slug": "_2-2-1-心跳包"
        },
        {
          "level": 2,
          "title": "2.2.2 数据包",
          "slug": "_2-2-2-数据包"
        },
        {
          "level": 2,
          "title": "2.2.3 其他语言的实现",
          "slug": "_2-2-3-其他语言的实现"
        }
      ]
    },
    {
      "title": "2.3 路由设计",
      "frontmatter": {},
      "regularPath": "/guide/v2/2.3.route.html",
      "relativePath": "guide/v2/2.3.route.md",
      "key": "v-30bba521",
      "path": "/guide/v2/2.3.route.html",
      "headers": [
        {
          "level": 2,
          "title": "2.3.1 路由注册",
          "slug": "_2-3-1-路由注册"
        },
        {
          "level": 2,
          "title": "2.3.2 路由状态",
          "slug": "_2-3-2-路由状态"
        },
        {
          "level": 2,
          "title": "2.3.3 无状态路由分发",
          "slug": "_2-3-3-无状态路由分发"
        },
        {
          "level": 2,
          "title": "2.3.4 有状态路由定向转发",
          "slug": "_2-3-4-有状态路由定向转发"
        },
        {
          "level": 2,
          "title": "2.3.5 消息流转",
          "slug": "_2-3-5-消息流转"
        }
      ]
    },
    {
      "title": "2.4 绑定网关",
      "frontmatter": {},
      "regularPath": "/guide/v2/2.4.bind-gate.html",
      "relativePath": "guide/v2/2.4.bind-gate.md",
      "key": "v-161a85fb",
      "path": "/guide/v2/2.4.bind-gate.html"
    },
    {
      "title": "2.5 绑定节点",
      "frontmatter": {},
      "regularPath": "/guide/v2/2.5.bind-node.html",
      "relativePath": "guide/v2/2.5.bind-node.md",
      "key": "v-91e8cbea",
      "path": "/guide/v2/2.5.bind-node.html"
    },
    {
      "title": "2.6 单线程模型",
      "frontmatter": {},
      "regularPath": "/guide/v2/2.6.single-thread.html",
      "relativePath": "guide/v2/2.6.single-thread.md",
      "key": "v-3e27a0cf",
      "path": "/guide/v2/2.6.single-thread.html"
    },
    {
      "title": "2.7 多协程模型",
      "frontmatter": {},
      "regularPath": "/guide/v2/2.7.multiple-coroutines.html",
      "relativePath": "guide/v2/2.7.multiple-coroutines.md",
      "key": "v-59af357b",
      "path": "/guide/v2/2.7.multiple-coroutines.html"
    },
    {
      "title": "2.8 Actor模型",
      "frontmatter": {},
      "regularPath": "/guide/v2/2.8.actor.html",
      "relativePath": "guide/v2/2.8.actor.md",
      "key": "v-67cf453f",
      "path": "/guide/v2/2.8.actor.html"
    },
    {
      "title": "2.9 启动配置",
      "frontmatter": {},
      "regularPath": "/guide/v2/2.9.etc.html",
      "relativePath": "guide/v2/2.9.etc.md",
      "key": "v-325ab3bf",
      "path": "/guide/v2/2.9.etc.html",
      "headers": [
        {
          "level": 2,
          "title": "2.9.1 基本介绍",
          "slug": "_2-9-1-基本介绍"
        },
        {
          "level": 2,
          "title": "2.9.2 指定目录",
          "slug": "_2-9-2-指定目录"
        },
        {
          "level": 2,
          "title": "2.9.3 支持格式",
          "slug": "_2-9-3-支持格式"
        },
        {
          "level": 2,
          "title": "2.9.4 读写规则",
          "slug": "_2-9-4-读写规则"
        },
        {
          "level": 2,
          "title": "2.9.5 相关接口",
          "slug": "_2-9-5-相关接口"
        },
        {
          "level": 2,
          "title": "2.9.6 示例代码",
          "slug": "_2-9-6-示例代码"
        },
        {
          "level": 2,
          "title": "2.9.7 全部配置",
          "slug": "_2-9-7-全部配置"
        }
      ]
    },
    {
      "title": "3.1 网关服务器",
      "frontmatter": {},
      "regularPath": "/guide/v2/3.1.gate.html",
      "relativePath": "guide/v2/3.1.gate.md",
      "key": "v-6fce4e79",
      "path": "/guide/v2/3.1.gate.html",
      "headers": [
        {
          "level": 2,
          "title": "3.1.1 基础介绍",
          "slug": "_3-1-1-基础介绍"
        },
        {
          "level": 2,
          "title": "3.1.2 TCP网关",
          "slug": "_3-1-2-tcp网关"
        },
        {
          "level": 2,
          "title": "3.1.2 WS网关",
          "slug": "_3-1-2-ws网关"
        }
      ]
    },
    {
      "title": "3.2 节点服务器",
      "frontmatter": {},
      "regularPath": "/guide/v2/3.2.node.html",
      "relativePath": "guide/v2/3.2.node.md",
      "key": "v-34b5c4b9",
      "path": "/guide/v2/3.2.node.html",
      "headers": [
        {
          "level": 2,
          "title": "3.2.1 基础介绍",
          "slug": "_3-2-1-基础介绍"
        },
        {
          "level": 2,
          "title": "3.2.2 调度模型",
          "slug": "_3-2-2-调度模型"
        },
        {
          "level": 2,
          "title": "3.2.3 示例代码",
          "slug": "_3-2-3-示例代码"
        }
      ]
    },
    {
      "title": "3.3 网格服务器",
      "frontmatter": {},
      "regularPath": "/guide/v2/3.3.mesh.html",
      "relativePath": "guide/v2/3.3.mesh.md",
      "key": "v-1084db0e",
      "path": "/guide/v2/3.3.mesh.html",
      "headers": [
        {
          "level": 2,
          "title": "3.3.1 基础介绍",
          "slug": "_3-3-1-基础介绍"
        },
        {
          "level": 2,
          "title": "3.3.2 GRPC示例",
          "slug": "_3-3-2-grpc示例"
        },
        {
          "level": 2,
          "title": "3.3.3 RPCX示例",
          "slug": "_3-3-3-rpcx示例"
        }
      ]
    },
    {
      "title": "4.1 注册中心",
      "frontmatter": {},
      "regularPath": "/guide/v2/4.1.registry.html",
      "relativePath": "guide/v2/4.1.registry.md",
      "key": "v-63fed0d9",
      "path": "/guide/v2/4.1.registry.html"
    },
    {
      "title": "3.4 Web服务器",
      "frontmatter": {},
      "regularPath": "/guide/v2/3.4.web.html",
      "relativePath": "guide/v2/3.4.web.md",
      "key": "v-85abd472",
      "path": "/guide/v2/3.4.web.html",
      "headers": [
        {
          "level": 2,
          "title": "3.4.1 基础介绍",
          "slug": "_3-4-1-基础介绍"
        },
        {
          "level": 2,
          "title": "3.4.2 跨域支持",
          "slug": "_3-4-2-跨域支持"
        },
        {
          "level": 2,
          "title": "3.4.3 Swagger支持",
          "slug": "_3-4-3-swagger支持"
        },
        {
          "level": 2,
          "title": "3.4.4 全局中间件",
          "slug": "_3-4-4-全局中间件"
        },
        {
          "level": 2,
          "title": "3.4.5 示例代码",
          "slug": "_3-4-5-示例代码"
        },
        {
          "level": 2,
          "title": "3.4.6 更多文档",
          "slug": "_3-4-6-更多文档"
        }
      ]
    },
    {
      "title": "4.2 配置中心",
      "frontmatter": {},
      "regularPath": "/guide/v2/4.2.config.html",
      "relativePath": "guide/v2/4.2.config.md",
      "key": "v-c93da84e",
      "path": "/guide/v2/4.2.config.html",
      "headers": [
        {
          "level": 2,
          "title": "4.2.1 基础介绍",
          "slug": "_4-2-1-基础介绍"
        },
        {
          "level": 2,
          "title": "4.2.2 支持格式",
          "slug": "_4-2-2-支持格式"
        },
        {
          "level": 2,
          "title": "4.2.3 读写规则",
          "slug": "_4-2-3-读写规则"
        },
        {
          "level": 2,
          "title": "4.2.4 相关接口",
          "slug": "_4-2-4-相关接口"
        },
        {
          "level": 2,
          "title": "4.2.5 自定义配置源",
          "slug": "_4-2-5-自定义配置源"
        },
        {
          "level": 2,
          "title": "4.2.6 file配置源示例",
          "slug": "_4-2-6-file配置源示例"
        },
        {
          "level": 2,
          "title": "4.2.7 consul配置源示例",
          "slug": "_4-2-7-consul配置源示例"
        },
        {
          "level": 2,
          "title": "4.2.8 etcd配置源示例",
          "slug": "_4-2-8-etcd配置源示例"
        },
        {
          "level": 2,
          "title": "4.2.9 nacos配置源示例",
          "slug": "_4-2-9-nacos配置源示例"
        },
        {
          "level": 2,
          "title": "4.2.10 自定义配置源示例",
          "slug": "_4-2-10-自定义配置源示例"
        },
        {
          "level": 2,
          "title": "启动配置 {#config-etc}",
          "slug": "启动配置-config-etc"
        }
      ]
    },
    {
      "title": "4.3 网络模块",
      "frontmatter": {},
      "regularPath": "/guide/v2/4.3.network.html",
      "relativePath": "guide/v2/4.3.network.md",
      "key": "v-24338093",
      "path": "/guide/v2/4.3.network.html",
      "headers": [
        {
          "level": 2,
          "title": "基本介绍 {#network-introduction}",
          "slug": "基本介绍-network-introduction"
        },
        {
          "level": 2,
          "title": "网络服务器示例 {#network-server-example}",
          "slug": "网络服务器示例-network-server-example"
        },
        {
          "level": 2,
          "title": "自定义网络服务器 {#network-custom-server}",
          "slug": "自定义网络服务器-network-custom-server"
        },
        {
          "level": 2,
          "title": "网络客户端示例 {#network-client-example}",
          "slug": "网络客户端示例-network-client-example"
        },
        {
          "level": 2,
          "title": "自定义网络客户端 {#network-custom-client}",
          "slug": "自定义网络客户端-network-custom-client"
        }
      ]
    },
    {
      "title": "4.4 传输模块",
      "frontmatter": {},
      "regularPath": "/guide/v2/4.4.transport.html",
      "relativePath": "guide/v2/4.4.transport.md",
      "key": "v-0dd2934a",
      "path": "/guide/v2/4.4.transport.html"
    },
    {
      "title": "4.5 日志模块",
      "frontmatter": {},
      "regularPath": "/guide/v2/4.5.log.html",
      "relativePath": "guide/v2/4.5.log.md",
      "key": "v-5b6ca83a",
      "path": "/guide/v2/4.5.log.html"
    },
    {
      "title": "4.6 缓存模块",
      "frontmatter": {},
      "regularPath": "/guide/v2/4.6.cache.html",
      "relativePath": "guide/v2/4.6.cache.md",
      "key": "v-5b4ccb25",
      "path": "/guide/v2/4.6.cache.html"
    },
    {
      "title": "4.7 加密模块",
      "frontmatter": {},
      "regularPath": "/guide/v2/4.7.crypto.html",
      "relativePath": "guide/v2/4.7.crypto.md",
      "key": "v-c4264dce",
      "path": "/guide/v2/4.7.crypto.html"
    },
    {
      "title": "4.8 事件总线",
      "frontmatter": {},
      "regularPath": "/guide/v2/4.8.eventbus.html",
      "relativePath": "guide/v2/4.8.eventbus.md",
      "key": "v-0d40aa99",
      "path": "/guide/v2/4.8.eventbus.html"
    },
    {
      "title": "4.9 分布式锁",
      "frontmatter": {},
      "regularPath": "/guide/v2/4.9.lock.html",
      "relativePath": "guide/v2/4.9.lock.md",
      "key": "v-3e753219",
      "path": "/guide/v2/4.9.lock.html"
    },
    {
      "title": "5.1 GORM",
      "frontmatter": {},
      "regularPath": "/guide/v2/5.1.gorm.html",
      "relativePath": "guide/v2/5.1.gorm.md",
      "key": "v-44839cb9",
      "path": "/guide/v2/5.1.gorm.html",
      "headers": [
        {
          "level": 2,
          "title": "5.1.1 第三方库",
          "slug": "_5-1-1-第三方库"
        },
        {
          "level": 2,
          "title": "5.1.2 配置参数",
          "slug": "_5-1-2-配置参数"
        },
        {
          "level": 2,
          "title": "5.1.3 示例代码",
          "slug": "_5-1-3-示例代码"
        }
      ]
    },
    {
      "title": "5.2 Redis",
      "frontmatter": {},
      "regularPath": "/guide/v2/5.2.redis.html",
      "relativePath": "guide/v2/5.2.redis.md",
      "key": "v-cfdec98e",
      "path": "/guide/v2/5.2.redis.html",
      "headers": [
        {
          "level": 2,
          "title": "5.2.1 第三方库",
          "slug": "_5-2-1-第三方库"
        },
        {
          "level": 2,
          "title": "5.2.2 配置参数",
          "slug": "_5-2-2-配置参数"
        },
        {
          "level": 2,
          "title": "5.2.3 示例代码",
          "slug": "_5-2-3-示例代码"
        }
      ]
    },
    {
      "title": "5.3 Mongo",
      "frontmatter": {},
      "regularPath": "/guide/v2/5.3.mongo.html",
      "relativePath": "guide/v2/5.3.mongo.md",
      "key": "v-cd672476",
      "path": "/guide/v2/5.3.mongo.html",
      "headers": [
        {
          "level": 2,
          "title": "5.3.1 第三方库",
          "slug": "_5-3-1-第三方库"
        },
        {
          "level": 2,
          "title": "5.3.2 配置参数",
          "slug": "_5-3-2-配置参数"
        },
        {
          "level": 2,
          "title": "5.3.3 示例代码",
          "slug": "_5-3-3-示例代码"
        }
      ]
    },
    {
      "title": "5.4 JWT",
      "frontmatter": {},
      "regularPath": "/guide/v2/5.4.jwt.html",
      "relativePath": "guide/v2/5.4.jwt.md",
      "key": "v-5bc3a49d",
      "path": "/guide/v2/5.4.jwt.html",
      "headers": [
        {
          "level": 2,
          "title": "5.4.1 第三方库",
          "slug": "_5-4-1-第三方库"
        },
        {
          "level": 2,
          "title": "5.2.2 配置参数",
          "slug": "_5-2-2-配置参数"
        },
        {
          "level": 2,
          "title": "5.4.3 示例代码",
          "slug": "_5-4-3-示例代码"
        }
      ]
    },
    {
      "title": "框架介绍",
      "frontmatter": {},
      "regularPath": "/guide/v2/",
      "relativePath": "guide/v2/README.md",
      "key": "v-59650e12",
      "path": "/guide/v2/",
      "headers": [
        {
          "level": 2,
          "title": "简介",
          "slug": "简介"
        },
        {
          "level": 2,
          "title": "架构",
          "slug": "架构"
        },
        {
          "level": 2,
          "title": "优势",
          "slug": "优势"
        },
        {
          "level": 2,
          "title": "功能",
          "slug": "功能"
        }
      ]
    },
    {
      "title": "加入开发群",
      "frontmatter": {},
      "regularPath": "/join/",
      "relativePath": "join/README.md",
      "key": "v-e8f5e2f6",
      "path": "/join/",
      "headers": [
        {
          "level": 2,
          "title": "加入开发群",
          "slug": "加入开发群"
        },
        {
          "level": 3,
          "title": "社区微信",
          "slug": "社区微信"
        },
        {
          "level": 3,
          "title": "群主微信",
          "slug": "群主微信"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "文档",
        "link": "/guide/v2/"
      },
      {
        "text": "相关项目",
        "items": [
          {
            "text": "聊天室",
            "link": "https://github.com/dobyte/due-chat"
          },
          {
            "text": "斗地主",
            "link": "https://github.com/dobyte/due-doudizhu-desc"
          }
        ]
      },
      {
        "text": "加入我们",
        "link": "/join/"
      },
      {
        "text": "GitHub",
        "link": "https://github.com/dobyte/due"
      }
    ],
    "repo": "dobyte/due-docs",
    "repoLabel": "查看文档源码",
    "docsDir": "docs",
    "docsBranch": "master",
    "editLinks": true,
    "editLinkText": "在github.com上编辑此页",
    "sidebar": {
      "/summary/": [
        ""
      ],
      "/guide/v2/": [
        {
          "title": "第1章 简介",
          "collapsable": false,
          "children": [
            "/guide/v2/1.1.quick-start",
            "/guide/v2/1.2.examples",
            "/guide/v2/1.3.contribute"
          ]
        },
        {
          "title": "第2章 框架设计",
          "collapsable": false,
          "children": [
            "/guide/v2/2.1.architecture",
            "/guide/v2/2.2.protocol",
            "/guide/v2/2.3.route",
            "/guide/v2/2.4.bind-gate",
            "/guide/v2/2.5.bind-node",
            "/guide/v2/2.6.single-thread",
            "/guide/v2/2.7.multiple-coroutines",
            "/guide/v2/2.8.actor",
            "/guide/v2/2.9.etc",
            "/guide/v2/2.10.mode",
            "/guide/v2/2.11.error",
            "/guide/v2/2.12.rolling-update"
          ]
        },
        {
          "title": "第3章 集群服务",
          "collapsable": false,
          "children": [
            "/guide/v2/3.1.gate",
            "/guide/v2/3.2.node",
            "/guide/v2/3.3.mesh",
            "/guide/v2/3.4.web"
          ]
        },
        {
          "title": "第4章 核心模块",
          "collapsable": false,
          "children": [
            "/guide/v2/4.1.registry",
            "/guide/v2/4.2.config",
            "/guide/v2/4.3.network",
            "/guide/v2/4.4.transport",
            "/guide/v2/4.5.log",
            "/guide/v2/4.6.cache",
            "/guide/v2/4.7.crypto",
            "/guide/v2/4.8.eventbus",
            "/guide/v2/4.9.lock"
          ]
        },
        {
          "title": "第5章 三方组件",
          "collapsable": false,
          "children": [
            "/guide/v2/5.1.gorm",
            "/guide/v2/5.2.redis",
            "/guide/v2/5.3.mongo",
            "/guide/v2/5.4.jwt"
          ]
        }
      ]
    },
    "sidebarDepth": 2,
    "lastUpdated": "上次更新",
    "serviceWorker": {
      "updatePopup": {
        "message": "发现新内容可用",
        "buttonText": "刷新"
      }
    }
  }
}