[jwt.default]
	# jwt发行方
	issuer = "due"
	# 过期时间（秒），默认7200s
	validDuration = 7200
	# 秘钥KEY
	secretKey = "xxxx"
	# 身份认证KEY
	identityKey = "uid"
	# TOKEN查找位置
	locations = "query:token,header:Authorization"
	# 存储组件
	[jwt.default.store]
		# 连接地址
        addrs = ["127.0.0.1:6379"]
        # 数据库号，默认为0
        db = 0
        # 用户名，默认空
        username = ""
        # 密码，默认空
        password = ""
        # 私钥文件
        keyFile = ""
        # 证书文件
        certFile = ""
        # CA证书文件
        caFile = ""
        # 网络相关的错误最大重试次数，默认3次
        maxRetries = 3
        # 最大连接池限制，默认为200个连接
        poolSize = 200
        # 最小空闲连接数，默认10个连接
        minIdleConns = 10
        # 拨号超时时间，支持单位：纳秒（ns）、微秒（us | µs）、毫秒（ms）、秒（s）、分（m）、小时（h）、天（d）。默认5s
        dialTimeout = "5s"
        # 连接最大空闲时间，支持单位：纳秒（ns）、微秒（us | µs）、毫秒（ms）、秒（s）、分（m）、小时（h）、天（d）。默认0s
        idleTimeout = "0s"
        # 读超时，支持单位：纳秒（ns）、微秒（us | µs）、毫秒（ms）、秒（s）、分（m）、小时（h）、天（d）。默认1s
        readTimeout = "1s"
        # 写超时，支持单位：纳秒（ns）、微秒（us | µs）、毫秒（ms）、秒（s）、分（m）、小时（h）、天（d）。默认1s
        writeTimeout = "1s"