# 进程号
pid = "./run/due.pid"
# 开发模式。支持模式：debug、test、release（设置优先级：配置文件 < 环境变量 < 运行参数 < mode.SetMode()）
mode = "debug"
# 统一时区设置。项目中的时间获取请使用xtime.Now()
timezone = "Local"
# 容器关闭最大等待时间。支持单位：纳秒（ns）、微秒（us | µs）、毫秒（ms）、秒（s）、分（m）、小时（h）、天（d）。默认为0
shutdownMaxWaitTime = "0s"

[cluster.mesh]
    # 实例ID，集群中唯一。不填写默认自动生成唯一的实例ID
    id = ""
    # 实例名称
    name = "mesh"
    # 是否将内部通信地址暴露到公网。默认为false
    expose = false
    # 编解码器。可选：json | proto。默认为proto
    codec = "proto"
    # 实例元数据
    [cluster.mesh.metadata]
        # 键值对，且均为字符串类型。由于注册中心的元数据参数限制，建议将键值对的数量控制在20个以内，键的字符长度控制在127个字符内，值得字符长度控制在512个字符内。
        key = "value"

[transport.rpcx.client]
    # CA证书文件
    caFile = ""
    # 证书域名
    serverName = ""
    # 连接池大小，默认为10
    poolSize = 10