# 进程号
pid = "./run/due.pid"
# 开发模式。支持模式：debug、test、release（设置优先级：配置文件 < 环境变量 < 运行参数 < mode.SetMode()）
mode = "debug"
# 统一时区设置。项目中的时间获取请使用xtime.Now()
timezone = "Local"
# 容器关闭最大等待时间。支持单位：纳秒（ns）、微秒（us | µs）、毫秒（ms）、秒（s）、分（m）、小时（h）、天（d）。默认为0
shutdownMaxWaitTime = "0s"

[http]
    # 服务器名称
    name = "http"
    # 服务器监听地址，默认为:8080
    addr = ":8080"
    # 是否启用控制台输出，默认为false
    console = false
    # body大小，支持单位： B | K | KB | M | MB | G | GB | T | TB | P | PB | E | EB | Z | ZB，默认为4 * 1024 * 1024
    bodyLimit = "4M"
    # 最大并发连接数，默认为256 * 1024
    concurrency = 262144
    # 是否启用严格路由模式，默认为false，启用后"/foo"与"/foo/"为两个不同的路由
    strictRouting = false
    # 是否区分路由大小写，默认为false， 启用后"/FoO"与"/foo"为两个不同的路由
    caseSensitive = false
    # 秘钥文件
    keyFile = ""
    # 证书文件
    certFile = ""
    # 跨域配置
    [http.cors]
        # 是否启用跨域
        enable = false
        # 允许跨域的请求源。默认为[]，即为允许所有请求源
        allowOrigins = []
        # 允许跨域的请求方法。默认为["GET", "POST", "HEAD", "PUT", "DELETE", "PATCH"]
        allowMethods = []
        # 允许跨域的请求头部。默认为[]，即为允许所有请求头部
        allowHeaders = []
        # 当允许所有源时，根据CORS规范不允许携带凭据。默认为false
        allowCredentials = false
        # 允许暴露给客户端的头部。默认为[]，即为允许暴露所有头部
        exposeHeaders = []
        # 浏览器缓存预检请求结果的时间。默认为0
        maxAge = 0
        # 是否允许来自私有网络的请求。设置为true时，响应头Access-Control-Allow-Private-Network会被设置为true。默认为false
        allowPrivateNetwork = false
    # swagger文档配置
    [http.swagger]
        # 是否启用文档
        enable = true
        # API文档标题
        title = "API文档"
        # URL访问基础路径
        basePath = "/swagger"
        # swagger文件路径
        filePath = "./docs/swagger.json"
        # swagger-ui-bundle.js地址。当系统默认的cdn失效时可替换为自己的cdn地址，默认为空，使用系统默认https://unpkg.com/swagger-ui@5.28.1/dist/swagger-ui.js
        swaggerBundleUrl = ""
        # swagger-ui-standalone-preset.js地址。当系统默认的cdn失效时可替换为自己的cdn地址，默认为空，使用系统默认https://unpkg.com/swagger-ui@5.28.1/dist/swagger-ui-standalone-preset.js
        swaggerPresetUrl = ""
        # swagger-ui.css地址。当系统默认的cdn失效时可替换为自己的cdn地址，默认为空，使用系统默认https://unpkg.com/swagger-ui@5.28.1/dist/swagger-ui.css
        swaggerStylesUrl = ""