[eventbus.nats]
    # 客户端连接地址，默认为nats://127.0.0.1:4222
    url = "nats://127.0.0.1:4222"
    # 客户端连接超时时间，支持单位：纳秒（ns）、微秒（us | µs）、毫秒（ms）、秒（s）、分（m）、小时（h）、天（d）。默认为2s
    timeout = "2s"
    # key前缀
    prefix = "due:eventbus"